/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ItineraryBuilderRouteImport } from './routes/itinerary-builder'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as CreateTripRouteImport } from './routes/create-trip'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryBuilderRoute = ItineraryBuilderRouteImport.update({
  id: '/itinerary-builder',
  path: '/itinerary-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTripRoute = CreateTripRouteImport.update({
  id: '/create-trip',
  path: '/create-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/budget': typeof BudgetRoute
  '/cities': typeof CitiesRoute
  '/community': typeof CommunityRoute
  '/create-trip': typeof CreateTripRoute
  '/itinerary': typeof ItineraryRoute
  '/itinerary-builder': typeof ItineraryBuilderRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/shared': typeof SharedRoute
  '/signup': typeof SignupRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/budget': typeof BudgetRoute
  '/cities': typeof CitiesRoute
  '/community': typeof CommunityRoute
  '/create-trip': typeof CreateTripRoute
  '/itinerary': typeof ItineraryRoute
  '/itinerary-builder': typeof ItineraryBuilderRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/shared': typeof SharedRoute
  '/signup': typeof SignupRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/budget': typeof BudgetRoute
  '/cities': typeof CitiesRoute
  '/community': typeof CommunityRoute
  '/create-trip': typeof CreateTripRoute
  '/itinerary': typeof ItineraryRoute
  '/itinerary-builder': typeof ItineraryBuilderRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/packing': typeof PackingRoute
  '/profile': typeof ProfileRoute
  '/shared': typeof SharedRoute
  '/signup': typeof SignupRoute
  '/trips': typeof TripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/budget'
    | '/cities'
    | '/community'
    | '/create-trip'
    | '/itinerary'
    | '/itinerary-builder'
    | '/login'
    | '/notes'
    | '/packing'
    | '/profile'
    | '/shared'
    | '/signup'
    | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/budget'
    | '/cities'
    | '/community'
    | '/create-trip'
    | '/itinerary'
    | '/itinerary-builder'
    | '/login'
    | '/notes'
    | '/packing'
    | '/profile'
    | '/shared'
    | '/signup'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/budget'
    | '/cities'
    | '/community'
    | '/create-trip'
    | '/itinerary'
    | '/itinerary-builder'
    | '/login'
    | '/notes'
    | '/packing'
    | '/profile'
    | '/shared'
    | '/signup'
    | '/trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  BudgetRoute: typeof BudgetRoute
  CitiesRoute: typeof CitiesRoute
  CommunityRoute: typeof CommunityRoute
  CreateTripRoute: typeof CreateTripRoute
  ItineraryRoute: typeof ItineraryRoute
  ItineraryBuilderRoute: typeof ItineraryBuilderRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  PackingRoute: typeof PackingRoute
  ProfileRoute: typeof ProfileRoute
  SharedRoute: typeof SharedRoute
  SignupRoute: typeof SignupRoute
  TripsRoute: typeof TripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary-builder': {
      id: '/itinerary-builder'
      path: '/itinerary-builder'
      fullPath: '/itinerary-builder'
      preLoaderRoute: typeof ItineraryBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-trip': {
      id: '/create-trip'
      path: '/create-trip'
      fullPath: '/create-trip'
      preLoaderRoute: typeof CreateTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  BudgetRoute: BudgetRoute,
  CitiesRoute: CitiesRoute,
  CommunityRoute: CommunityRoute,
  CreateTripRoute: CreateTripRoute,
  ItineraryRoute: ItineraryRoute,
  ItineraryBuilderRoute: ItineraryBuilderRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  PackingRoute: PackingRoute,
  ProfileRoute: ProfileRoute,
  SharedRoute: SharedRoute,
  SignupRoute: SignupRoute,
  TripsRoute: TripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
